services:
  - name: web
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /

  - name: keep-alive
    buildCommand: npm install
    startCommand: ts-node keep-alive.ts
